# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SAIOT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ScrollableGraphView', '4.0.4'
  pod 'SwiftyHue', '0.4.1'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  # Pods for SAIOT

end
